# Site settings
title: Samuel C. Lee
email: samleenz@me.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Research Assistant with PRaDA at Deakin University, Australia.
  I study transcriptomics of complex diseases using standard statistical frameworks and machine learning. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://samleenz.github.io/" # the base hostname & protocol for your site
twitter_username: samleechch
github_username:  samleenz
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
